# Generated by Django 2.0.2 on 2018-02-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='flat_no',
        ),
    ]
