# Generated by Django 2.0.2 on 2018-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ab', '0002_remove_address_flat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='flat_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
