# Generated by Django 2.0.2 on 2018-03-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ab', '0005_auto_20180301_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
    ]
